name: GHPages Validate
# NOTE: This is designed to work for a site living in the /docs folder. You'll need to make changes if it is not.
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev


concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ./docs/.nvmrc
          cache-dependency-path: ./docs/package.json
          cache: yarn

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ./docs/public
            ./docs/.cache
          key: ${{ runner.os }}-gatsby-build-${{ hashFiles('public') }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-

      - name: Install dependencies
        working-directory: ./docs
        run: yarn install
        
      - name: Build with Gatsby
        working-directory: ./docs
        env:
          PREFIX_PATHS: 'true'
        run: yarn run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./docs/public
