# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/nick/Library/Application Support/QGIS/QGIS3/profiles/test/python/plugins/RIPTPlugin/src/ui/zoi_type_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_zoi_type_dialog(object):
    def setupUi(self, zoi_type_dialog):
        zoi_type_dialog.setObjectName("zoi_type_dialog")
        zoi_type_dialog.resize(531, 334)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/nick/Library/Application Support/QGIS/QGIS3/profiles/test/python/plugins/RIPTPlugin/src/ui/../../icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        zoi_type_dialog.setWindowIcon(icon)
        self.formLayout = QtWidgets.QFormLayout(zoi_type_dialog)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(zoi_type_dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit_zoi_type_name = QtWidgets.QLineEdit(zoi_type_dialog)
        self.lineEdit_zoi_type_name.setObjectName("lineEdit_zoi_type_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_zoi_type_name)
        self.label_2 = QtWidgets.QLabel(zoi_type_dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.comboBox_zoi_influence = QtWidgets.QComboBox(zoi_type_dialog)
        self.comboBox_zoi_influence.setObjectName("comboBox_zoi_influence")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_zoi_influence)
        self.label_5 = QtWidgets.QLabel(zoi_type_dialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.plainTextEdit_zoi_type_description = QtWidgets.QPlainTextEdit(zoi_type_dialog)
        self.plainTextEdit_zoi_type_description.setObjectName("plainTextEdit_zoi_type_description")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.plainTextEdit_zoi_type_description)
        self.buttonBox = QtWidgets.QDialogButtonBox(zoi_type_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.buttonBox)

        self.retranslateUi(zoi_type_dialog)
        QtCore.QMetaObject.connectSlotsByName(zoi_type_dialog)

    def retranslateUi(self, zoi_type_dialog):
        _translate = QtCore.QCoreApplication.translate
        zoi_type_dialog.setWindowTitle(_translate("zoi_type_dialog", "ZOI Type"))
        self.label.setText(_translate("zoi_type_dialog", "ZOI Type Name"))
        self.lineEdit_zoi_type_name.setPlaceholderText(_translate("zoi_type_dialog", "E.g.,  Bank Erosion"))
        self.label_2.setText(_translate("zoi_type_dialog", "Influence Type"))
        self.label_5.setText(_translate("zoi_type_dialog", "ZOI Type Description"))
        self.plainTextEdit_zoi_type_description.setPlaceholderText(_translate("zoi_type_dialog", "Description of hydrologic,  hydraulic,  geomorphic,  biologica,l  and/or ecological processes."))
