# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/philip/code/riverscapes/QRiS/src/view/ui/experimental/structure_type_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_design_dialog(object):
    def setupUi(self, design_dialog):
        design_dialog.setObjectName("design_dialog")
        design_dialog.resize(662, 517)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/philip/code/riverscapes/QRiS/src/view/ui/experimental/../../icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        design_dialog.setWindowIcon(icon)
        self.formLayout = QtWidgets.QFormLayout(design_dialog)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(design_dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit_structure_type_name = QtWidgets.QLineEdit(design_dialog)
        self.lineEdit_structure_type_name.setObjectName("lineEdit_structure_type_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_structure_type_name)
        self.label_2 = QtWidgets.QLabel(design_dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.comboBox_structure_mimics = QtWidgets.QComboBox(design_dialog)
        self.comboBox_structure_mimics.setObjectName("comboBox_structure_mimics")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_structure_mimics)
        self.label_5 = QtWidgets.QLabel(design_dialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.plainTextEdit_construction_description = QtWidgets.QPlainTextEdit(design_dialog)
        self.plainTextEdit_construction_description.setObjectName("plainTextEdit_construction_description")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.plainTextEdit_construction_description)
        self.label_7 = QtWidgets.QLabel(design_dialog)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.plainTextEdit_function_description = QtWidgets.QPlainTextEdit(design_dialog)
        self.plainTextEdit_function_description.setObjectName("plainTextEdit_function_description")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.plainTextEdit_function_description)
        self.label_9 = QtWidgets.QLabel(design_dialog)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.lineEdit_typical_posts = QtWidgets.QLineEdit(design_dialog)
        self.lineEdit_typical_posts.setText("")
        self.lineEdit_typical_posts.setObjectName("lineEdit_typical_posts")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit_typical_posts)
        self.label_8 = QtWidgets.QLabel(design_dialog)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_typical_length = QtWidgets.QLineEdit(design_dialog)
        self.lineEdit_typical_length.setText("")
        self.lineEdit_typical_length.setObjectName("lineEdit_typical_length")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit_typical_length)
        self.label_4 = QtWidgets.QLabel(design_dialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_typical_width = QtWidgets.QLineEdit(design_dialog)
        self.lineEdit_typical_width.setText("")
        self.lineEdit_typical_width.setObjectName("lineEdit_typical_width")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lineEdit_typical_width)
        self.label_6 = QtWidgets.QLabel(design_dialog)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_typical_height = QtWidgets.QLineEdit(design_dialog)
        self.lineEdit_typical_height.setText("")
        self.lineEdit_typical_height.setObjectName("lineEdit_typical_height")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.lineEdit_typical_height)
        self.buttonBox = QtWidgets.QDialogButtonBox(design_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.buttonBox)

        self.retranslateUi(design_dialog)
        QtCore.QMetaObject.connectSlotsByName(design_dialog)

    def retranslateUi(self, design_dialog):
        _translate = QtCore.QCoreApplication.translate
        design_dialog.setWindowTitle(_translate("design_dialog", "Create Structure Type"))
        self.label.setText(_translate("design_dialog", "Structure Type Name"))
        self.lineEdit_structure_type_name.setPlaceholderText(_translate("design_dialog", "E.g., Large BDA"))
        self.label_2.setText(_translate("design_dialog", "Structure Mimics"))
        self.label_5.setText(_translate("design_dialog", "Construction Description"))
        self.plainTextEdit_construction_description.setPlaceholderText(_translate("design_dialog", "Description of materials,  mathods,  dimensions, and construction considerations. "))
        self.label_7.setText(_translate("design_dialog", "Function Description"))
        self.plainTextEdit_function_description.setPlaceholderText(_translate("design_dialog", "What is this structure designed to do? E.g., cause ponding and overbank flow during typical floods."))
        self.label_9.setText(_translate("design_dialog", "Typical Posts"))
        self.lineEdit_typical_posts.setToolTip(_translate("design_dialog", "<html><head/><body><p>Typical number of posts used to construct this structure type.</p></body></html>"))
        self.lineEdit_typical_posts.setPlaceholderText(_translate("design_dialog", "e.g.,  14"))
        self.label_8.setText(_translate("design_dialog", "Typical Length"))
        self.lineEdit_typical_length.setToolTip(_translate("design_dialog", "<html><head/><body><p>Typical length of this structure type in meters.</p></body></html>"))
        self.lineEdit_typical_length.setPlaceholderText(_translate("design_dialog", "e.g., 5.1"))
        self.label_4.setText(_translate("design_dialog", "Typical Width"))
        self.lineEdit_typical_width.setPlaceholderText(_translate("design_dialog", "e.g.,  3.0"))
        self.label_6.setText(_translate("design_dialog", "Typical Height"))
        self.lineEdit_typical_height.setPlaceholderText(_translate("design_dialog", "e.g.,  0.50"))
